### ISSUE TITLE
Error: CordovaError: No platforms added to this project. Please use `cordova platform add <platform>`.

### ISSUE THREAD

**Issue by hbmartin** [donvigo/steps-cordova-android#1]
Hi, thanks for this! When I to build my project I get:
Error: CordovaError: No platforms added to this project. Please use `cordova platform add <platform>`.

What am I doing wrong?

**Comment by vgaidarji** [comment]
Hey. Do you have an Android platform added to your Cordova project? [3rd step](https://cordova.apache.org)

It should like [this](https://github.com/vgaidarji/cordova-android-sample/tree/master/platforms/android) in your project. I've used this project to test step in bitrise.io.

**Comment by hbmartin** [comment]
I added script to run `cordova platform add android` before this plugin step.
After that I no longer saw this error.
I also had to manually set JAVA_HOME env var.

**Comment by vgaidarji** [comment]
`JAVA_HOME` should exist in every Android build on bitrise as it runs on Android stack which has preinstalled Java and exported appropriate env vars.
I didn't set it in my workflows and worked for me fine.
